/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BreatheRouteImport } from './routes/breathe'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistDashboardRouteImport } from './routes/therapist/dashboard'
import { Route as SessionBookingIdRouteImport } from './routes/session.$bookingId'
import { Route as OrgDashboardRouteImport } from './routes/org/dashboard'
import { Route as BookingTherapistIdRouteImport } from './routes/booking.$therapistId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BreatheRoute = BreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistDashboardRoute = TherapistDashboardRouteImport.update({
  id: '/therapist/dashboard',
  path: '/therapist/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionBookingIdRoute = SessionBookingIdRouteImport.update({
  id: '/session/$bookingId',
  path: '/session/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgDashboardRoute = OrgDashboardRouteImport.update({
  id: '/org/dashboard',
  path: '/org/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTherapistIdRoute = BookingTherapistIdRouteImport.update({
  id: '/booking/$therapistId',
  path: '/booking/$therapistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/breathe': typeof BreatheRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/subscription': typeof SubscriptionRoute
  '/therapists': typeof TherapistsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/booking/$therapistId': typeof BookingTherapistIdRoute
  '/org/dashboard': typeof OrgDashboardRoute
  '/session/$bookingId': typeof SessionBookingIdRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/breathe': typeof BreatheRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/subscription': typeof SubscriptionRoute
  '/therapists': typeof TherapistsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/booking/$therapistId': typeof BookingTherapistIdRoute
  '/org/dashboard': typeof OrgDashboardRoute
  '/session/$bookingId': typeof SessionBookingIdRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/breathe': typeof BreatheRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/subscription': typeof SubscriptionRoute
  '/therapists': typeof TherapistsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/booking/$therapistId': typeof BookingTherapistIdRoute
  '/org/dashboard': typeof OrgDashboardRoute
  '/session/$bookingId': typeof SessionBookingIdRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/breathe'
    | '/chat'
    | '/dashboard'
    | '/journal'
    | '/mood'
    | '/onboarding'
    | '/sign-in'
    | '/subscription'
    | '/therapists'
    | '/admin/dashboard'
    | '/api/chat'
    | '/booking/$therapistId'
    | '/org/dashboard'
    | '/session/$bookingId'
    | '/therapist/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/breathe'
    | '/chat'
    | '/dashboard'
    | '/journal'
    | '/mood'
    | '/onboarding'
    | '/sign-in'
    | '/subscription'
    | '/therapists'
    | '/admin/dashboard'
    | '/api/chat'
    | '/booking/$therapistId'
    | '/org/dashboard'
    | '/session/$bookingId'
    | '/therapist/dashboard'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/breathe'
    | '/chat'
    | '/dashboard'
    | '/journal'
    | '/mood'
    | '/onboarding'
    | '/sign-in'
    | '/subscription'
    | '/therapists'
    | '/admin/dashboard'
    | '/api/chat'
    | '/booking/$therapistId'
    | '/org/dashboard'
    | '/session/$bookingId'
    | '/therapist/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  BreatheRoute: typeof BreatheRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  JournalRoute: typeof JournalRoute
  MoodRoute: typeof MoodRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TherapistsRoute: typeof TherapistsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ApiChatRoute: typeof ApiChatRoute
  BookingTherapistIdRoute: typeof BookingTherapistIdRoute
  OrgDashboardRoute: typeof OrgDashboardRoute
  SessionBookingIdRoute: typeof SessionBookingIdRoute
  TherapistDashboardRoute: typeof TherapistDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathe': {
      id: '/breathe'
      path: '/breathe'
      fullPath: '/breathe'
      preLoaderRoute: typeof BreatheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist/dashboard': {
      id: '/therapist/dashboard'
      path: '/therapist/dashboard'
      fullPath: '/therapist/dashboard'
      preLoaderRoute: typeof TherapistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$bookingId': {
      id: '/session/$bookingId'
      path: '/session/$bookingId'
      fullPath: '/session/$bookingId'
      preLoaderRoute: typeof SessionBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/dashboard': {
      id: '/org/dashboard'
      path: '/org/dashboard'
      fullPath: '/org/dashboard'
      preLoaderRoute: typeof OrgDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$therapistId': {
      id: '/booking/$therapistId'
      path: '/booking/$therapistId'
      fullPath: '/booking/$therapistId'
      preLoaderRoute: typeof BookingTherapistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  BreatheRoute: BreatheRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  JournalRoute: JournalRoute,
  MoodRoute: MoodRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SubscriptionRoute: SubscriptionRoute,
  TherapistsRoute: TherapistsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ApiChatRoute: ApiChatRoute,
  BookingTherapistIdRoute: BookingTherapistIdRoute,
  OrgDashboardRoute: OrgDashboardRoute,
  SessionBookingIdRoute: SessionBookingIdRoute,
  TherapistDashboardRoute: TherapistDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
